{
  "by" : "bratao",
  "descendants" : 25,
  "id" : 38196188,
  "kids" : [ 38196504, 38196641, 38196750, 38196518, 38196559, 38196636, 38196502, 38196659, 38196848, 38196715, 38196439, 38196586, 38196576 ],
  "score" : 55,
  "time" : 1699474079,
  "title" : "Another Major Outage Across ChatGPT and API",
  "type" : "story",
  "url" : "https://status.openai.com/incidents/21vl32gvx3hb"
}
